-- initialization
DROP SCHEMA IF EXISTS user01 CASCADE;
DROP DATABASE IF EXISTS user01;
CREATE DATABASE user01;
CREATE USER user01 WITH PASSWORD 'secret';
CREATE SCHEMA AUTHORIZATION user01;
GRANT ALL PRIVILEGES ON SCHEMA user01 TO user01;
