spring:
  liquibase:
    enabled: false
#    default-schema: ${DB_SCHEMA}
#  datasource.hikari.schema: ${DB_USER}
---
spring.config.activate.on-profile: debug
logging.level:
  org.hibernate.SQL: trace
  org.hibernate.type.descriptor.sql.BasicBinder: trace
  org.hibernate.type: trace
  com.zaxxer.hikari: trace
spring.jpa.properties.hibernate:
  show_sql: true
  use_sql_comments: true
  format_sql: true
---
spring.config.activate.on-profile: h2
spring.liquibase.parameters:
  clob.type: varchar(2048)
  float.type: float4
  now: now()
---
spring.config.activate.on-profile: postgres
spring.liquibase.parameters:
  clob.type: varchar(2048)
  float.type: float4
  now: current_timestamp
spring.datasource:
  username: ${DB_USER}
  password: ${DB_PASSWORD}
#  url: jdbc:postgresql://localhost:65501/
  url: jdbc:postgresql://localhost:65501/${DB_NAME}
---
spring.config.activate.on-profile: mysql
spring.liquibase.parameters:
  clob.type: varchar(2048)
  float.type: float
  now: now()
spring.datasource:
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  url: jdbc:mysql://localhost:65502/${DB_SCHEMA}
---
spring.config.activate.on-profile: oracle
spring.liquibase.parameters:
  clob.type: varchar(2048)
  float.type: float
  now: sysdate
spring.datasource:
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  url: jdbc:oracle:thin:@localhost:65503:xe
---
spring.config.activate.on-profile: mssql
spring.liquibase.parameters:
  clob.type: varchar(2048)
  float.type: float
  now: current_timestamp
spring.datasource:
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  url: jdbc:sqlserver://localhost:65504;databaseName=${DB_NAME}
---
### sqlite: current_timestamp

spring.config.activate.on-profile: liquibase-migrate
spring:
  main:
    web-application-type: none
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.task.TaskSchedulingConfiguration
  liquibase: 
    enabled: true
