spring:
  liquibase: 
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    username: postgres
    password: secret
    url: jdbc:postgresql://server1:25432/
---
spring:
  config:
    activate:
      on-profile: liquibase-migrate
  main:
    web-application-type: none
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.task.TaskSchedulingConfiguration
  liquibase: 
    enabled: true
