spring:
  liquibase: 
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.xml
#  datasource:
#    username: postgres
#    password: secret
#    url: jdbc:postgresql://localhost:5432/
---
spring:
  config:
    activate:
      on-profile: liquibase-wipe
  main:
    web-application-type: none
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.task.TaskSchedulingConfiguration
  liquibase: 
    enabled: true
