spring:
  liquibase:
    enabled: false
    default-schema: user01
  datasource.hikari.schema: user01
---
spring.config.activate.on-profile: debug
logging.level:
  org.hibernate.SQL: trace
  org.hibernate.type.descriptor.sql.BasicBinder: trace
  org.hibernate.type: trace
  com.zaxxer.hikari: trace
spring.jpa.properties.hibernate:
  show_sql: true
  use_sql_comments: true
  format_sql: true
---
spring.config.activate.on-profile: h2
spring.liquibase.parameters:
  clob.type: varchar(2048)
  float.type: float4
  now: now()
---
spring.config.activate.on-profile: postgres
spring.liquibase.parameters:
  clob.type: varchar(2048)
  float.type: float4
  now: current_timestamp
spring.datasource:
  username: user01
  password: secret
  url: jdbc:postgresql://localhost:65501/user01_db
#?user=user01
#?user=user01"
#/user01?currentSchema=user01
---
spring.config.activate.on-profile: mysql
spring.liquibase.parameters:
  clob.type: varchar(2048)
  float.type: float
  now: now()
spring.datasource:
  username: user01
  password: secret
  url: jdbc:mysql://localhost:65502/user01
---
spring.config.activate.on-profile: oracle
spring.liquibase.parameters:
  clob.type: varchar(2048)
  float.type: float
  now: sysdate
spring.datasource:
  username: USER01
  password: secret
  url: jdbc:oracle:thin:@localhost:65503:xe
---
spring.config.activate.on-profile: liquibase-migrate
spring:
  main:
    web-application-type: none
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.task.TaskSchedulingConfiguration
  liquibase: 
    enabled: true
