spring:
  liquibase:
    enabled: false
  #  change-log: classpath:db/changelog/ex.db.changelog-master.xml
  # default datasource H2
---
spring.config.activate.on-profile: postgres
spring.liquibase.parameters:
  clobType: clob
spring.datasource:
  username: postgres
  password: secret
  url: jdbc:postgresql://${HOST}:25432/
---
spring.config.activate.on-profile: liquibase-migrate
spring:
  main:
    web-application-type: none
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.task.TaskSchedulingConfiguration
  liquibase: 
    enabled: true
